# Generated by Django 5.0.8 on 2024-08-08 13:28
from __future__ import annotations

import datetime
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LotteryBallots",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("game_date", models.DateField(default=datetime.datetime.today)),
                ("is_winner", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="WinningBallots",
            fields=[
                (
                    "winning_ballot_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("draw_date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
